### PR TITLE
Update language grammars to be more in line with Sublime conventions

### PR DESCRIPTION
**Pull request by ccampbell**
Hi there. I have been working on some swift projects lately, and I absolutely cannot stand Xcode. Unfortunately, I was also not able to find a really great Sublime Text syntax grammar for Swift. Yours definitely comes the closest out of the ones I tried. I decided to make a few changes and offer them back to you.

This change introduces a bunch of tweaks/improvements to the syntax including:

- Switches to use storage or variable scopes in places where entity was
being used incorrectly
- Updates start and end brackets scope to be more generic using `punctuation.section.block`
- Updates `class` definition to use keyword as opposed to storage
- Updates argument labels in function declarations to use new scope
- Updates import syntax to be more like other languages
- Adds support for static keyword
- Adds support for `#selector` and `#available` methods
- Adds some missing tests to code blocks in the syntax_test_swift file
- Adds support for variable and function declarations within struct
blocks

These changes are not exhaustive, but should make things match up more closely with other languages in Sublime Text.

Related to sublimehq/Packages#11

---

## Screenshots

To give you an idea of what the changes look like visually

### Before

syntax before

### After

syntax after

### CODE REVIEW

**Comment by ccampbell** [comment]
Added one more commit with a `tmPreferences` file for comments.

**Comment by jrappen** [comment]
While you're at it it might also make sense to add a GitHub Action workflow as found in:

`./.github/workflows/ci.yml`

at:

https://github.com/sublimehq/Packages

while updating the Build number for the test binary used, as we are at 4112 and not 4094 for the dev channel as stated in the workflow for the Packages repo. Keep in mind, that the workflow in the Packages repo has a subfolder structure and this repo doesn't. You'll have to adjust accordingly. Specifically you'll want to create "Data/Packages/Swift" and move files and folders into there.

**Comment by GregoryBL** [comment]
Hi, and thank you for the contribution! Sorry for the merge conflict - I set up CI and had to fix a few things to get it to pass (thanks for the details @jrappen).

Otherwise this looks good.

**Comment by FichteFoll** [comment]
As an aside, you could also use https://github.com/marketplace/actions/sublime-text-syntax-tests.

**Comment by ccampbell** [comment]
> Hi, and thank you for the contribution! Sorry for the merge conflict - I set up CI and had to fix a few things to get it to pass (thanks for the details @jrappen).
> 
> Otherwise this looks good.

Thanks. I just rebased with your changes from master so it should no longer have any conflicts. One thing I did not change cause I wasn’t sure about the proper scope is the `struct` keyword itself. Looking at a few languages that have structs, go uses `keyword.declaration.struct.go`, C uses `keyword.declaration.c`, rust uses `storage.type.struct.rust`, and this package is currently using `storage.type.struct.swift`. @FichteFoll do you have any recommendations here?

**Comment by FichteFoll** [comment]
`keyword.declaration` should be the way to go. You can then further specialize that to `keyword.declaration.struct.swift`.

**Pull request merged**
